### ISSUE TITLE
Power BI reports not listed

### ISSUE THREAD

**Issue by rameshkumar-arumugam** [fuel9/DisplayMonkey#19]
Hi ,

I have created reports in Power Bi and make them as public. I have configured the Azure account in display monkey as per your documentation.
I try to create a new frame with Power Bi reports "Remote server returns 404" issue has been thrown.
Can you please help me to resolve this issue?

Regards,
Rameshkumar Arumugam.

**Comment by DisplayMonkey** [comment]
Hi, welcome to DM!
Which version of DM do you have installed?
Are you running DM on prom or in the cloud?

**Comment by rameshkumar-arumugam** [comment]
Hi,

This issue has been fixed by changed the API URL. I have checked the below link,
http://docs.powerbi.apiary.io/#reference/report/reports-collection/list-all-dashboards
I have replaced the "Tenant Id" with "myorg"  in API URL and its working fine now.
Thanks, guys.

Regards,
Rameshkumar Arumugam.

**Comment by DisplayMonkey** [comment]
Hi, thanks for your input. You may find useful that Tennant Id can be specified in DMM report frame screen. Could you please share how exactly did you change the API URL?

**Comment by DisplayMonkey** [comment]
Our apologies, Tenant Id can be specified under the Azure account settings. Please see the attached screenshot.
![display_monkey_2__running_](https://user-images.githubusercontent.com/13225024/26879219-e3a4679a-4b55-11e7-8bf8-1ebcf27abefb.png)

Please note that the Tenant Id is only necessary when your organization chooses to create one.

**Comment by rameshkumar-arumugam** [comment]
Hi Guys,

I have checked this by my organization account. So I gave tenant Id when creating Microsoft  Azure account. I face an issue while getting reports from Power bi then I debug the report listing code in Power bi controller and removed the following code, 

![image](https://user-images.githubusercontent.com/29115412/26912551-e25afaf6-4c32-11e7-946a-a7ef8303c2f4.png)

Let me know if you have any queries,

Regards,
Rameshkumar Arumugam.

**Comment by DisplayMonkey** [comment]
We are glad that the above solution works for you. 

Unfortunately, we cannot recommend your solution to the users community, as it does not provide for method to properly pass the Tenant ID from designated application screens, which is offered by the original design. You could have achieved the same behavior by filling-in "myorg" value into the Tenant ID field under the Azure account settings, or simply leaving it blank.

Regarding debugging issues. Some debugging issues may arise in VS due to the fact that you are attempting to debug an async method.

We are closing this issue.

Thanks for giving DisplayMonkey a spin!

**Comment by DisplayMonkey** [comment]
We had reconsidered this issue and are adjusting the code in such way that "myorg" remains static in the URL. We wanted to compliment  @rameshkumar-arumugam for his valuable contribution.
