### ISSUE TITLE
Reuse of frame in multiple panels/canvases

### ISSUE THREAD

**Issue by jaschrock** [fuel9/DisplayMonkey#22]
I am not sure if this is the general forum site or only for bugs, etc. Sorry if it is the wrong thing. 

We are looking at having several displays with the exact same layout but a few different items. So, for things like an HTML frame, I would like to have that same HTML frame on multiple panels/canvases so that when we need to change it to say something else, it would be deployed to all locations. It seems a frame is tied to one and only one canvas. Maybe the frame templates do this (I could handle that possibly with an HTML frame type but without the WYSIWYG editor) but I am not sure.  We could live without some of the "extras" but it would be nice at each of our rooms (we are looking at room entry booking/displays) to be able to have some content that can easily be edited for the day or week but not have to edit each frame individually.
Thanks
Alan

**Comment by DisplayMonkey** [comment]
Hi Alan,

Hopefully I'm reading you right, otherwise please feel free to correct me.

You are right – every frame belongs to one panel (and canvas) at a time.

However, there are a couple different ways in which you can accomplish what you want.

The first, and the simplest, would be to create a boilerplate canvas with all the shared panels and frames. Then you can use the copy function to create multiple copies of your boilerplate canvas, assign them to actual displays, fill-in monitor-specific frames and you should be done. Depending on the frequency of changes in the content, there might be some maintenance involved with this method.

The other method is a little trickier to implement, but may take less maintenance down the road. It can take advantage of frames ability to link specific locations. Basically, you can define one location per monitor (or a group of monitors) and then designate certain frames to those locations, so they render on relevant monitors only. Leave all other frames location-independent, so that they render on all monitors.

The frame HTML templates are primarily designed to give you ability to meet certain layout requirements, like background color, font, spacing and so on. It is not really meant to be used for dynamic content, although it could contain simple java script and style blocks. In case of HTML frame, however, the entire thing is rendered in an iframe, so there is not much you can do with HTML templates here.

Hope this helps.

We are about to push some updates to DisplayMonkey very shortly, so stay tuned.

**Comment by jaschrock** [comment]
Hi Denis,
Yes, I think you get my concept. What I am doing is looking at implementing a monitor at every door (to replace an existing door catalog system that links to an outlook calendar). So, for the most part if I put a weather frame in, a clock frame in, these would be the same for all. But, I will need to customize the outlook frame since each room is tied to a different outlook calendar. Then, I thought I would add a common html block that could be used for special information that would go onto all monitors (the location independent frame). I was figuring I needed to do a canvas per room in order to handle the different outlook frame for each room. I could easily create a location per room as well if that would work. 
I like the concept you are presenting in the second paragraph as I think that is what I am looking to do. I don't see, though, how to assign a frame to a different panel/canvas (or location). I only see assigning a frame to a panel and then panels are assigned to canvases.  

I like the product, I think it may very well work for our application. And, we may not even need this specific feature (and I could use an iframe or other method to handle it potentially as well). Just thought it would be nice to have frames that would be on multiple canvases (via panels) and can be edited from one location - mainly HTML block - some of the rest don't make sense to do that with. 

Thanks

Alan

**Comment by DisplayMonkey** [comment]
Hi Alan, you can designate frame to a location as shown on the snippet below:

![display_monkey_2__running_](https://user-images.githubusercontent.com/13225024/29188403-97ab26c0-7dd8-11e7-9cb9-e3939df15608.png)

then:

![display_monkey_2__running_ 2](https://user-images.githubusercontent.com/13225024/29188468-c17b0bd2-7dd8-11e7-9971-d285d805e7a0.png)

Note that you may designate multiple locations to the same frame:

![display_monkey_2__running_ 3](https://user-images.githubusercontent.com/13225024/29188564-15f072ba-7dd9-11e7-822b-51706e15325f.png)

Hope this helps.

Enjoy DisplayMonkey!

**Comment by jaschrock** [comment]
I hadn't looked at the view of the frame only the edit and create so didn't notice that. It worked. Thanks!

Alan

**Comment by djstevematthews** [comment]
Hi! How where is the copy function to copy multiple canvas you speak of please. I need to make a large amount of screens all with different outlook info so need to find the best way to do this. I assume i will need to make a canvas, panel assignment for every different screen.

**Comment by michaelmalmgren** [comment]
Hi @djstevematthews, there is no copy function from the UI however you should be able to "copy" by interacting directly with the Display Monkey SQL database.

**Comment by psined1** [comment]
There is a copy canvas function - a button in UI on canvas detail screen. It copies one canvas at a time, optionally along with panels and frames. Hope this helps.
