### ISSUE TITLE
GIf that get uploaded not animated

### ISSUE THREAD

**Issue by PeteK209** [fuel9/DisplayMonkey#33]
anyone know how to fix this? any gifs that are being uploaded only show the first screen and not the animation. seems to be lost in the upload.

**Comment by psined1** [comment]
Sorry, I take back on the #2 option - the Crop will equally transform the original picture if either of its' dimensions exceeds that of a panel. Otherwise the original image will be used. So use with caution. Similarly, if both picture and panel dimensions match, no transformation occurs and the picture will show as is.
